[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
authors = [
  { name="eagle", email="eagle@42.fr" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
